# Generated by Django 2.1.4 on 2019-08-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelsystem',
            name='sign',
            field=models.DateField(auto_now=True, null=True, verbose_name='最后签到日期'),
        ),
    ]
