# Generated by Django 2.1.4 on 2019-08-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_auto_20190809_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userimg',
            field=models.TextField(default=1, verbose_name='用户头像编码'),
            preserve_default=False,
        ),
    ]
